use_frameworks!

platform :ios, '16.0'

#def common_pods
#  pod 'Kingfisher', '~> 7.0'
#end

target 'Core_Example' do
  pod 'Core', :path => '../'

  target 'Core_Tests' do
    inherit! :search_paths    
  end
end
